### ISSUE TITLE
Hey Eddie!

### ISSUE THREAD

**Issue by ghost** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#47]

**Comment by EddyVerbruggen** [comment]
Just add a comment to one of those other issues instead of creating duplicates.

And please add some details about the devices you've tested with (both hardware and firmware), how you are testing, and what exactly isn't working. A stacktrace also helps, as well as checking if an older version of this plugin did help.

Those things are relevant, anything else isn't.
